spring:
  security:
    filter:
      order: -100
    jwt:
      key: abcdef
      expire: 7
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123123
    url: jdbc:mysql://localhost:3306/bm_login
  web:
    cors:
      origin: '*'
      credentials: false
      methods: '*'